import json

with open('./config.json', 'r', encoding='UTF8') as f:
    config = json.load(f)

SECRET_KEY = config['DEFAULT']['SECRET_KEY']

DATABASE_POSTGRESQL_URL = config['DEFAULT']['DATABASE_POSTGRESQL_URL']
DATABASE_POSTGRESQL_PORT = config['DEFAULT']['DATABASE_POSTGRESQL_PORT']
DATABASE_POSTGRESQL_DBNAME = config['DEFAULT']['DATABASE_POSTGRESQL_DBNAME']
DATABASE_POSTGRESQL_USERNAME = config['DEFAULT']['DATABASE_POSTGRESQL_USERNAME']
DATABASE_POSTGRESQL_PASSWORD = config['DEFAULT']['DATABASE_POSTGRESQL_PASSWORD']

# 키클록(SSO) 설정
KEYCLOAK_SERVER_URL = config['DEFAULT']['KEYCLOAK_SERVER_URL']
KEYCLOAK_REALM = config['DEFAULT']['KEYCLOAK_REALM']
KEYCLOAK_CLIENT_ID = config['DEFAULT']['KEYCLOAK_CLIENT_ID']
KEYCLOAK_CLIENT_SECRET = config['DEFAULT']['KEYCLOAK_CLIENT_SECRET']

# GPT_OSS 앞 데이터 제거하는 기준값
GPT_OSS_MAX_INPUT_TOKENS = config['DEFAULT']['GPT_OSS_MAX_INPUT_TOKENS']

# 보안검사 관련 파일들 위치
SECURE_BEARER_BIN_PATH = config['DEFAULT']['SECURE_BEARER_BIN_PATH']
SECURE_BEARER_RULE_PATH = config['DEFAULT']['SECURE_BEARER_RULE_PATH']

SUMMARY_MODEL_URL = config['DEFAULT'].get('summary_model_url')
SUMMARY_MODEL_ID = config['DEFAULT'].get('summary_model_id')

